export enum ORDER_STATUS {
	PENDING = "PENDING",
	APPROVED = "APPROVED",
	REJECTED = "REJECTED",
	CANCELED = "CANCELED",
	COMPLETE = "COMPLETE",
}

export enum ROLE {
	ADMIN = "ROLE_ADMIN",
	DOCTOR = "ROLE_DOCTOR",
	USER = "ROLE_USER",
}

export const FORMAT_HOUR = "h:mm A";
